# Generated by Django 5.1.2 on 2024-11-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_perfil_carrinho_salvo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco1',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco2',
            new_name='endereco',
        ),
    ]
