# Generated by Django 5.1.2 on 2024-11-09 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_endereco1_perfil_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='pais',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', message='ATENÇÃO! CEP deve estar no formato XXXXX-XXX.')]),
        ),
    ]
