# Generated by Django 5.1.2 on 2024-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoentrega',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
