# Generated by Django 5.1.2 on 2024-10-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_enderecoentrega_complemento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecoentrega',
            options={'verbose_name_plural': 'Endereços de Entrega'},
        ),
    ]
