# Generated by Django 5.1.2 on 2024-10-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_alter_enderecoentrega_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='cep',
            new_name='ent_cep',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='cidade',
            new_name='ent_cidade',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='complemento',
            new_name='ent_complemento',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='email',
            new_name='ent_email',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='endereco',
            new_name='ent_endereco',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='estado',
            new_name='ent_estado',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='nome',
            new_name='ent_nome',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='pais',
            new_name='ent_pais',
        ),
        migrations.RenameField(
            model_name='enderecoentrega',
            old_name='user',
            new_name='usuario',
        ),
    ]
