# Generated by Django 5.1.2 on 2024-11-09 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0007_pedido_data_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecoentrega',
            name='ent_pais',
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='ent_cep',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', message='ATENÇÃO! CEP deve estar no formato XXXXX-XXX.')]),
        ),
    ]
